# Generated by Django 4.2.1 on 2023-06-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='Tel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
