# Generated by Django 4.2.1 on 2023-06-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_shippingaddress_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='Tel',
        ),
        migrations.AlterField(
            model_name='product',
            name='digit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
