# Generated by Django 4.2.1 on 2023-06-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digit',
            new_name='digital',
        ),
    ]
