# Generated by Django 4.2.1 on 2023-06-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_digit_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
