# Generated by Django 4.2.1 on 2023-06-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_category_product_author_product_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
